part: Fix build error when SPL_NVME is enabled
When SPL is enabled but SPL_ENV_SUPPORT is disabled the build breaks
with the link error:
riscv64-unknown-linux-gnu-ld.bfd: disk/part.o: in function
`blk_get_device_part_str':
u-boot/disk/part.c:474: undefined reference to `env_get'
Fix the issue by calling env_get only if ENV_SUPPORT is enabled.

Signed-off-by: Mayuresh Chitale <mchitale@ventanamicro.com>